log clarity fix

diff --git a/.github/workflows/reuse-updater.yml b/.github/workflows/reuse-updater.yml
--- a/.github/workflows/reuse-updater.yml
+++ b/.github/workflows/reuse-updater.yml
@@ -53,15 +53,18 @@ jobs:
           git config user.name "${{ env.CHANGELOG_USER }}"
           git config user.email "${{ env.CHANGELOG_EMAIL }}"
           git add -A
-          git commit -m "${{ env.REUSE_MESSAGE }}" || echo "No changes to commit or committing failed."
-          for i in {1..5}; do
-            git pull --rebase origin ${{ vars.CHANGELOG_BRANCH }} || exit 1
-            if git push origin ${{ vars.CHANGELOG_BRANCH }}; then
-              echo "Push succeeded"
-              exit 0
-            fi
-            echo "Push failed, retrying in 5s..."
-            sleep 5
-          done
-          echo "Push failed after 5 attempts."
-          exit 1
+          if git commit -m "${{ env.REUSE_MESSAGE }}"; then
+            for i in {1..5}; do
+              git pull --rebase origin ${{ vars.CHANGELOG_BRANCH }} || exit 1
+              if git push origin ${{ vars.CHANGELOG_BRANCH }}; then
+                echo "Push succeeded"
+                exit 0
+              fi
+              echo "Push failed, retrying in 5s..."
+              sleep 5
+            done
+            echo "Push failed after 5 attempts."
+            exit 1
+          else
+            echo "No changes to commit or committing failed."
+          fi
